### PR TITLE
Issue #13, 

### PR DESCRIPTION
**Pull request by soumilk**
placed the files in the described structure but havent changed the server.py, couldn't figure out how to change it. Help needed

### CODE REVIEW

**Comment by theSage21** [comment]
So you've removed all files and created the expected folder structure. There is still some work left in this PR:

- you need to supply the input, output, statement files for at least one question (Question 1). Other question folders you can delete.
- The following lines need to have the new file paths:
    - https://github.com/PyJaipur/PyJudge/blob/master/server.py#L32
    - https://github.com/PyJaipur/PyJudge/blob/master/server.py#L44

**Comment by soumilk** [comment]
Is this the correct one?
`
from bottle import Bottle, run, template, static_file, request, route
import os
import sys
path = os.path.abspath(__file__)
dir_path = os.path.dirname(path)

app = Bottle()

with open('./files/question/1/expected.txt', 'r') as fl:
    expected = fl.read()

@app.get('/question/<number>')
def question1(number):
    return static_file('statement.html', root=dir_path)

@app.get('/question/<number>/input.txt/')
def download(number):
    input_file_name = 'inputs'+number+'.txt'
    return static_file(inputs.txt, root=dir_path+'/'+'files/questions/')

@app.route('/upload', method = 'POST')
def file_upload():
    uploaded = request.files.get('upload').file.read() #uploaded outputs by user
    global expected
    expected = expected.strip()
    uploaded = uploaded.strip()
    ans = (uploaded==expected)

    if not ans:
        return "Wrong Answer!!"
    else: 
        return "Solved! Great Job!"


run(app, host='localhost', port=8080)
`

**Comment by theSage21** [comment]
can we please not have code in the comments? Just push new commits.

**Comment by theSage21** [comment]
I think it will be easier for you if you simply close this PR and open a fresh one.

**Comment by theSage21** [comment]
no need to merge. I think @soumilk will need to create a new PR with the proper changes.

**Pull request closed without merging**
