### PR TITLE
sample question have been added. please read description

### PR DESCRIPTION
**Pull request by Shivank98**
here it is only a sample question and also contains a download link for the input file. the output needs to be generated from input. I guess @arnabsinha99 is working with that.
I still think this PR can be improved so I seek review.

i used `/question/<number>` so we can further put more question in same pattern.

### CODE REVIEW

**Comment by theSage21** [comment]
This request attempts to solve two things at once. #2  and #5 
We can wait for a merge request for issue #2 before merging or you can attempt to factor your solution into two files. One python file for the server and one html file for the question statement.

**Comment by Shivank98** [comment]
sounds right. I will wait for @rustagishubhi

**Comment by theSage21** [comment]
This can be updated to reflect changes introduced by solving #2 ?

**Comment by Shivank98** [comment]
On it

**Comment by Shivank98** [comment]
please review @theSage21

**Comment by Shivank98** [comment]
yeah right, will try best to make it good.

**Comment by Shivank98** [comment]
```<!--Main Part-->
	<div class="highlight">
		<div class="row">
			<div class="column column-20">
				
			</div>
			<div class="column">
				<div class="shift-center">
					<p><!--Question-->Add Two Given Numbers.</p>
					<a href="/question/1/download/">Download Test Case></a>
				</div>
			</div>
		    <div class="column column-20">
				
			</div>
		</div>
```

```
@app.get('/question/<number>')
def question(number):
    return static_file('index.html' , root=dir_path)
  



@app.get('/question/<number>/download/')
def download(number):
    input_file_name = 'inputs'+number+'.txt'
    return static_file(input_file_name, root=dir_path+'/'+'files/questions/')
```

**Comment by Shivank98** [comment]
i have made changes in HTML file so it will have a link to submit. as discussed in last comment

**Comment by Shivank98** [comment]
@theSage21 sounds cool for now ?

**Comment by theSage21** [comment]
This is fine for now.

**Pull request merged**
