### PR TITLE
integrated 'black' into project

### PR DESCRIPTION
**Pull request by rishabhKalakoti**
- [x] My title is a short description of what I am trying to do
- [x] I have mentioned all the issues I am fixing
- [x] Proposed changes

### CODE REVIEW

**Comment by rishabhKalakoti** [comment]
had to merge the changes. idk why but all my commits appeared again.

**Comment by theSage21** [comment]
I think you'll also have to install `pre-commit` in the pipenv? That should change the pipfile and the lock file

**Comment by theSage21** [comment]
also, I think you did not create this branch from master?

**Comment by rishabhKalakoti** [comment]
I ran `pip install pre-commit ` in the pipenv shell. I did it again, but the pipfile did not change. I did install black outside too. Should I remove it first?

**Comment by theSage21** [comment]
you'll need to run `pipenv install`

**Comment by rishabhKalakoti** [comment]
I think i got it right this time :)

**Comment by theSage21** [comment]
I think the approach is fine but you'll have to start a new PR. This current branch is polluted. Why don't you start from a clean branch.

1. synchronize your master branch with pyjaipur master
2. create a new branch
3. `pipenv --rm`
4. `pipenv --deploy`
5. `pipenv install pre-commit black`
6. commit and create PR

**Comment by rishabhKalakoti** [comment]
Ok. I will close this one.

**Pull request closed without merging**
