### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by theSage21**
# Thank You for your contribution to the *PyJudge*

- [ ] My title is a short description of what I am trying to do
- [ ] I have mentioned all the issues I am fixing
- [ ] Proposed changes

### CODE REVIEW

**Comment by theSage21** [comment]
@kirtibajaj please merge this

**Comment by kirtibajaj** [comment]
Ok

**Comment by rishabhKalakoti** [comment]
Why was this one closed?

**Comment by theSage21** [comment]
Why don't you open a new merge request with the license. Since I opened this one I can't merge

**Comment by theSage21** [comment]
let's go with MIT

**Pull request closed without merging**
